### ISSUE TITLE
弄了一下午终于跑通了。。效果一般

### ISSUE THREAD

**Issue by Water2style** [huihua-season/ALPR#1]
Lz有方法提高 对视频检测的准确率吗~

**Comment by EdisonPeee** [comment]
Hi @Water2style  請問 'No module named 'utils.box_utils' 你是如何打通的？

**Comment by ulanbator** [comment]
你好，能加个联系方式交流一下吗，我目前也在做类似的一个方向。

**Comment by kubl88** [comment]
请问这个问题 No module named 'utils.box_utils'，怎么解决的呢？谢谢

**Comment by SherlockSalvatore** [comment]
> 请问这个问题 No module named 'utils.box_utils'，怎么解决的呢？谢谢

同这个情况。。。有解决吗QAQ

**Comment by SherlockSalvatore** [comment]
> Lz有方法提高 对视频检测的准确率吗~

好哥哥，能说说是怎么弄的嘛。。。
